### ISSUE TITLE
Use latest NAIP for smaller scales for Hybrid

### ISSUE THREAD

**Issue by stdavis** [agrc-widgets/layer-selector#39]
There's been talk of people missing seeing the nicer looking NAIP at the smaller scales. I wonder if we could build that into this widget when specifying the `Hybrid` base map layer.

**Comment by steveoh** [comment]
I dont understand? Would that mean not using the Google imagery?

**Comment by stdavis** [comment]
Do I need to translate this to Español? ;)

Yes, it would mean using the latest NAIP service on discover at the smaller scale levels and then switching to the google imagery service at the larger scale levels. Just like we did with the UTM Hybrid service, only we would have to do it with JS on the client side.

**Comment by steveoh** [comment]
What scale level should this run up until do you think?

**Comment by stdavis** [comment]
1:4515 is what we did for the UTM version.

**Comment by stdavis** [comment]
This was accomplished from within the discover appliance. Ref: https://gis.utah.gov/new-services-on-discover/
